# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Jihong Ju's Blog"
header-img: "img/pexels-photo-1258740.jpeg"
email: ir.jihong.ju@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    "".
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: jihongju
medium_username: jihongju
linkedin_username: jihongju
twitter_username: jujihong
email_username: ir.jihong.ju@gmail.com
copyright_name: Jihong Ju

timezone: Europe/Amsterdam

google_tracking_id: UA-141669919-1

# Build settings
markdown: kramdown
# mathjax: true
# theme: minima
highlighter: rouge
permalink: pretty
paginate: 20
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
sass:
  sass_dir: _sass
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
disqus:
  shortname: jihongju-github-io
